# ====== Settings for DeathControl ======
# IMPORTANT: Do NOT use tabs in this file! Only use spaces!
# 
# Documentation on how to set up this configuration can be found here:
# http://dev.bukkit.org/server-mods/deathcontrol/pages/configuration/


disable-permissions: false
logging-level: standard

multi-world:
    allow-cross-world: true
    disabled-worlds: []

handlings:
    demo:
        priority-order: 1
        timeout-on-disconnect: 15
        conditions:
        - cause fall suicide
        - food-level > 0
        actions:
        - keep-items
        - keep-experience
        - message You're %victim-name% and %death-cause-formatted%.
        - message %plugin-prefix%This is an example message adjustable in the config.
