name: DeathControl
main: bone008.bukkit.deathcontrol.DeathControl
version: 1.3
author: Bone008
description: Allows items to be kept when a player dies for specific reasons.
softdepend: [Register,Permissions]

commands:
    death:
        usage: |
            /<command> help  for more information!
        aliases: [deathcontrol, dc]


permissions:
    deathcontrol.*:
        description: Gives access to all permissions
        children:
            deathcontrol.use: true
            deathcontrol.free: true
            deathcontrol.admin: true
    deathcontrol.use:
        default: true
        description: Allows the general use of this plugin
    deathcontrol.free:
        default: op
        description: Bypasses the cost for a death
    deathcontrol.admin:
        default: op
        description: Allows to reload the config files